/*
 * Generated by JasperReports - 18/04/18 13:27
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;



/**
 *
 */
public class test1_1524072462087_865911 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_FILTER = null;
    private JRFillParameter parameter_JASPER_REPORT = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_JASPER_REPORTS_CONTEXT = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_CONTEXT = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_SORT_FIELDS = null;
    private JRFillField field_hora_apertura = null;
    private JRFillField field_tipo = null;
    private JRFillField field_origen_id_oficina = null;
    private JRFillField field_origen_id_ciudad = null;
    private JRFillField field_origen_nombre = null;
    private JRFillField field_sistema = null;
    private JRFillField field_municipio = null;
    private JRFillField field_provincia = null;
    private JRFillField field_hora_cierre = null;
    private JRFillField field_pais = null;
    private JRFillField field_origen_id_municipio = null;
    private JRFillField field_oficina = null;
    private JRFillField field_sucursal = null;
    private JRFillField field_ciudad = null;
    private JRFillField field_origen_id = null;
    private JRFillField field_origen_mac = null;
    private JRFillField field_origen_id_sistema = null;
    private JRFillField field_origen_modelo = null;
    private JRFillField field_origen_ip = null;
    private JRFillField field_origen_id_tipo = null;
    private JRFillField field_origen_id_sucursal = null;
    private JRFillField field_origen_id_provincia = null;
    private JRFillField field_origen_id_pais = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_MASTER_CURRENT_PAGE = null;
    private JRFillVariable variable_MASTER_TOTAL_PAGES = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_origen_id_pais_COUNT = null;
    private JRFillVariable variable_Group1_COUNT = null;
    private JRFillVariable variable_Group2_COUNT = null;
    private JRFillVariable variable_origen_modelo_COUNT = null;
    private JRFillVariable variable_origen_mac_COUNT = null;
    private JRFillVariable variable_origen_id_tipo_COUNT = null;
    private JRFillVariable variable_origen_id_sistema_COUNT = null;
    private JRFillVariable variable_origen_id_sucursal_COUNT = null;
    private JRFillVariable variable_origen_id_oficina_COUNT = null;
    private JRFillVariable variable_origen_id_municipio_COUNT = null;
    private JRFillVariable variable_origen_id_ciudad_COUNT = null;
    private JRFillVariable variable_origen_ip_COUNT = null;
    private JRFillVariable variable_origen_id_provincia_COUNT = null;
    private JRFillVariable variable_hora_apertura_COUNT = null;
    private JRFillVariable variable_hora_cierre_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_FILTER = (JRFillParameter)pm.get("FILTER");
        parameter_JASPER_REPORT = (JRFillParameter)pm.get("JASPER_REPORT");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_JASPER_REPORTS_CONTEXT = (JRFillParameter)pm.get("JASPER_REPORTS_CONTEXT");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_CONTEXT = (JRFillParameter)pm.get("REPORT_CONTEXT");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_SORT_FIELDS = (JRFillParameter)pm.get("SORT_FIELDS");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_hora_apertura = (JRFillField)fm.get("hora_apertura");
        field_tipo = (JRFillField)fm.get("tipo");
        field_origen_id_oficina = (JRFillField)fm.get("origen_id_oficina");
        field_origen_id_ciudad = (JRFillField)fm.get("origen_id_ciudad");
        field_origen_nombre = (JRFillField)fm.get("origen_nombre");
        field_sistema = (JRFillField)fm.get("sistema");
        field_municipio = (JRFillField)fm.get("municipio");
        field_provincia = (JRFillField)fm.get("provincia");
        field_hora_cierre = (JRFillField)fm.get("hora_cierre");
        field_pais = (JRFillField)fm.get("pais");
        field_origen_id_municipio = (JRFillField)fm.get("origen_id_municipio");
        field_oficina = (JRFillField)fm.get("oficina");
        field_sucursal = (JRFillField)fm.get("sucursal");
        field_ciudad = (JRFillField)fm.get("ciudad");
        field_origen_id = (JRFillField)fm.get("origen_id");
        field_origen_mac = (JRFillField)fm.get("origen_mac");
        field_origen_id_sistema = (JRFillField)fm.get("origen_id_sistema");
        field_origen_modelo = (JRFillField)fm.get("origen_modelo");
        field_origen_ip = (JRFillField)fm.get("origen_ip");
        field_origen_id_tipo = (JRFillField)fm.get("origen_id_tipo");
        field_origen_id_sucursal = (JRFillField)fm.get("origen_id_sucursal");
        field_origen_id_provincia = (JRFillField)fm.get("origen_id_provincia");
        field_origen_id_pais = (JRFillField)fm.get("origen_id_pais");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_MASTER_CURRENT_PAGE = (JRFillVariable)vm.get("MASTER_CURRENT_PAGE");
        variable_MASTER_TOTAL_PAGES = (JRFillVariable)vm.get("MASTER_TOTAL_PAGES");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_origen_id_pais_COUNT = (JRFillVariable)vm.get("origen_id_pais_COUNT");
        variable_Group1_COUNT = (JRFillVariable)vm.get("Group1_COUNT");
        variable_Group2_COUNT = (JRFillVariable)vm.get("Group2_COUNT");
        variable_origen_modelo_COUNT = (JRFillVariable)vm.get("origen_modelo_COUNT");
        variable_origen_mac_COUNT = (JRFillVariable)vm.get("origen_mac_COUNT");
        variable_origen_id_tipo_COUNT = (JRFillVariable)vm.get("origen_id_tipo_COUNT");
        variable_origen_id_sistema_COUNT = (JRFillVariable)vm.get("origen_id_sistema_COUNT");
        variable_origen_id_sucursal_COUNT = (JRFillVariable)vm.get("origen_id_sucursal_COUNT");
        variable_origen_id_oficina_COUNT = (JRFillVariable)vm.get("origen_id_oficina_COUNT");
        variable_origen_id_municipio_COUNT = (JRFillVariable)vm.get("origen_id_municipio_COUNT");
        variable_origen_id_ciudad_COUNT = (JRFillVariable)vm.get("origen_id_ciudad_COUNT");
        variable_origen_ip_COUNT = (JRFillVariable)vm.get("origen_ip_COUNT");
        variable_origen_id_provincia_COUNT = (JRFillVariable)vm.get("origen_id_provincia_COUNT");
        variable_hora_apertura_COUNT = (JRFillVariable)vm.get("hora_apertura_COUNT");
        variable_hora_cierre_COUNT = (JRFillVariable)vm.get("hora_cierre_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.lang.String)field_origen_id_pais.getValue()); //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = ((java.lang.String)field_origen_id.getValue()); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = ((java.lang.String)field_pais.getValue()); //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = ((java.lang.String)field_provincia.getValue()); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = ((java.lang.String)field_municipio.getValue()); //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = ((java.lang.String)field_ciudad.getValue()); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = ((java.lang.String)field_origen_nombre.getValue()); //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = ((java.lang.String)field_oficina.getValue()); //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = new SimpleDateFormat("HH:mm:ss").format(((java.sql.Time)field_hora_apertura.getValue())); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = new SimpleDateFormat("HH:mm:ss").format(((java.sql.Time)field_hora_cierre.getValue())); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = ((java.lang.String)field_origen_modelo.getValue()); //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = ((java.lang.String)field_origen_mac.getValue()); //$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = ((java.lang.String)field_origen_id_tipo.getValue()); //$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = ((java.lang.String)field_origen_id_sistema.getValue()); //$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = ((java.lang.String)field_origen_id_sucursal.getValue()); //$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = ((java.lang.String)field_origen_id_oficina.getValue()); //$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = ((java.lang.String)field_origen_id_municipio.getValue()); //$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = ((java.lang.String)field_origen_id_ciudad.getValue()); //$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = ((java.lang.String)field_origen_ip.getValue()); //$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = ((java.lang.String)field_origen_id_provincia.getValue()); //$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = ((java.sql.Time)field_hora_apertura.getValue()); //$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = ((java.sql.Time)field_hora_cierre.getValue()); //$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = ((java.lang.Integer)variable_REPORT_COUNT.getValue())%2 == 0; //$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = " " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()); //$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = "Page "+((java.lang.Integer)variable_PAGE_NUMBER.getValue())+" of"; //$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=64$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.lang.String)field_origen_id_pais.getOldValue()); //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = ((java.lang.String)field_origen_id.getOldValue()); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = ((java.lang.String)field_pais.getOldValue()); //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = ((java.lang.String)field_provincia.getOldValue()); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = ((java.lang.String)field_municipio.getOldValue()); //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = ((java.lang.String)field_ciudad.getOldValue()); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = ((java.lang.String)field_origen_nombre.getOldValue()); //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = ((java.lang.String)field_oficina.getOldValue()); //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = new SimpleDateFormat("HH:mm:ss").format(((java.sql.Time)field_hora_apertura.getOldValue())); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = new SimpleDateFormat("HH:mm:ss").format(((java.sql.Time)field_hora_cierre.getOldValue())); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = ((java.lang.String)field_origen_modelo.getOldValue()); //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = ((java.lang.String)field_origen_mac.getOldValue()); //$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = ((java.lang.String)field_origen_id_tipo.getOldValue()); //$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = ((java.lang.String)field_origen_id_sistema.getOldValue()); //$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = ((java.lang.String)field_origen_id_sucursal.getOldValue()); //$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = ((java.lang.String)field_origen_id_oficina.getOldValue()); //$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = ((java.lang.String)field_origen_id_municipio.getOldValue()); //$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = ((java.lang.String)field_origen_id_ciudad.getOldValue()); //$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = ((java.lang.String)field_origen_ip.getOldValue()); //$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = ((java.lang.String)field_origen_id_provincia.getOldValue()); //$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = ((java.sql.Time)field_hora_apertura.getOldValue()); //$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = ((java.sql.Time)field_hora_cierre.getOldValue()); //$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = ((java.lang.Integer)variable_REPORT_COUNT.getOldValue())%2 == 0; //$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = " " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()); //$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = "Page "+((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())+" of"; //$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=64$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.lang.String)field_origen_id_pais.getValue()); //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = ((java.lang.String)field_origen_id.getValue()); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = ((java.lang.String)field_pais.getValue()); //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = ((java.lang.String)field_provincia.getValue()); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = ((java.lang.String)field_municipio.getValue()); //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = ((java.lang.String)field_ciudad.getValue()); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = ((java.lang.String)field_origen_nombre.getValue()); //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = ((java.lang.String)field_oficina.getValue()); //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = new SimpleDateFormat("HH:mm:ss").format(((java.sql.Time)field_hora_apertura.getValue())); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = new SimpleDateFormat("HH:mm:ss").format(((java.sql.Time)field_hora_cierre.getValue())); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = ((java.lang.String)field_origen_modelo.getValue()); //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = ((java.lang.String)field_origen_mac.getValue()); //$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = ((java.lang.String)field_origen_id_tipo.getValue()); //$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = ((java.lang.String)field_origen_id_sistema.getValue()); //$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = ((java.lang.String)field_origen_id_sucursal.getValue()); //$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = ((java.lang.String)field_origen_id_oficina.getValue()); //$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = ((java.lang.String)field_origen_id_municipio.getValue()); //$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = ((java.lang.String)field_origen_id_ciudad.getValue()); //$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = ((java.lang.String)field_origen_ip.getValue()); //$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = ((java.lang.String)field_origen_id_provincia.getValue()); //$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = ((java.sql.Time)field_hora_apertura.getValue()); //$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = ((java.sql.Time)field_hora_cierre.getValue()); //$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = ((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue())%2 == 0; //$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = " " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()); //$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = "Page "+((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())+" of"; //$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=64$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
